[package]
name = "pr-wallet-core"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
pr-protocol-types.workspace = true
pr-crypto.workspace = true
pr-commitment-tree.workspace = true
pr-joinsplit.workspace = true
serde.workspace = true
ml-kem = { version = "=0.2.1", features = ["deterministic"] }
kem = "=0.3.0-pre.0"
chacha20poly1305 = "=0.10.1"
rand_core = { version = "0.6.4", features = ["getrandom"] }
hex.workspace = true
serde_json.workspace = true
